import "@repo/ui/globals.css";
import { cn } from "@repo/ui/lib/utils";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Web",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className={cn(GeistSans.className, "dark")}>
      <body>{children}</body>
    </html>
  );
}
